{{- if .Values.canary.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "novapay.fullname" . }}
  labels:
    {{- include "novapay.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      {{- include "novapay.selectorLabels" . | nindent 6 }}
  strategy:
    canary:
      stableService: {{ include "novapay.fullname" . }}
      canaryService: {{ include "novapay.fullname" . }}-canary
      trafficRouting:
        istio:
          virtualService:
            name: {{ include "novapay.fullname" . }}
            routes:
              - novapay-primary
      steps:
        {{- range .Values.canary.phases }}
        - setWeight: {{ .trafficPercent }}
        - pause:
            duration: {{ .durationMinutes }}m
        {{- end }}
  template:
    metadata:
      labels:
        {{- include "novapay.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "novapay.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: novapay
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http
{{- end }}
