apiVersion: v1
kind: Service

metadata:
  name: {{ include "novapay.fullname" . }}
  labels:
    {{- include "novapay.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}

  selector:
    {{- include "novapay.selectorLabels" . | nindent 4 }}

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP

---

apiVersion: v1
kind: Service

metadata:
  name: {{ include "novapay.fullname" . }}-canary
  labels:
    {{- include "novapay.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}

  selector:
    {{- include "novapay.selectorLabels" . | nindent 4 }}

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP