name: novapay CI/CD pipeline
on: 
  workflow_dispatch:
    inputs:
      enviorments:
         description: 'enviorment to deploy'
         required: true
         default: 'staging'

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run YAML Lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .
          config_data: |
            extend: default
            ignore: |
              **/templates/
              charts
          
          strict: true
          
      - name: Testing workflow
        run: echo "workflow works!"

  
         
